version: "3.1"

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.online" # Must be an email for login
      PGADMIN_DEFAULT_PASSWORD: "test@2021#"
    ports:
      - "127.0.0.1:6000:80"

  postgres:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test123"
      POSTGRES_DB: "fullstack"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    container_name: "redis"
    image: "redis"
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - "redisdata:/data"

volumes:
  pgdata:
  redisdata:
